# Generated by Django 4.2.3 on 2023-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brands",
            options={"verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="features",
            options={"verbose_name_plural": "Features"},
        ),
        migrations.AlterModelOptions(
            name="models",
            options={"verbose_name_plural": "Models"},
        ),
        migrations.RemoveField(
            model_name="features",
            name="models",
        ),
        migrations.AddField(
            model_name="models",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="models", to="showroom.features"
            ),
        ),
    ]
