# Generated by Django 4.2.3 on 2023-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_alter_brands_options_alter_features_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="engine_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
