# Generated by Django 4.2.3 on 2023-07-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_alter_engine_engine_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engine",
            name="engine_number",
        ),
    ]
