# Generated by Django 4.2.3 on 2023-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0008_remove_engine_engine_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="engine_number",
            field=models.CharField(default=3, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
